### ISSUE TITLE
ベンチマーカーの実行方法

### ISSUE THREAD

**Issue by Goryudyuma** [recruit-tech/r-isucon#1]
https://github.com/recruit-tech/r-isucon#benchmark-bootup

非公開でしょうか？

**Comment by yosuke-furukawa** [comment]
@Goryudyuma すいません、しばしお待ち下さい。

@orisano できる時間があれば公開をお願いします。

**Comment by orisano** [comment]
#4 で修正しました

**Comment by Goryudyuma** [comment]
ありがとうございます！！
